# Generated by Django 3.0.8 on 2020-07-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mental_Health_Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Client', 'Client'), ('Business', 'Business')], default='Client', max_length=8)),
                ('resume', models.FileField(upload_to='')),
                ('background', models.CharField(max_length=100)),
                ('stability_index', models.IntegerField()),
                ('mental_health_scores', models.IntegerField()),
                ('sentence', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('job_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], default='Unemployed', max_length=10)),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Care')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Certification')),
                ('mental_health_tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Mental_Health_Tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
