# Generated by Django 3.0.8 on 2020-07-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_care_certification_mental_health_tests_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
